// <auto-generated />
using Ch04MovieListDahlstrom.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ch04MovieListDahlstrom.Migrations.Ticket
{
    [DbContext(typeof(TicketContext))]
    [Migration("20260320194845_AddTicket")]
    partial class AddTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Ch04MovieListDahlstrom.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PointValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SprintNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            Description = "Create solution and project files",
                            Name = "Setup Project",
                            PointValue = 3,
                            SprintNumber = 1,
                            Status = "To Do"
                        },
                        new
                        {
                            TicketId = 2,
                            Description = "Add Ticket model and Movie model",
                            Name = "Create Models",
                            PointValue = 5,
                            SprintNumber = 1,
                            Status = "In Progress"
                        },
                        new
                        {
                            TicketId = 3,
                            Description = "Implement Index view for tickets",
                            Name = "Build Views",
                            PointValue = 8,
                            SprintNumber = 2,
                            Status = "QA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
